### ISSUE TITLE
Где файл ui.trustersetupdialog.h

### ISSUE THREAD

**Issue by VAFA0000** [Timarrr/RovUI2#5]
Где файл ui.trustersetupdialog.h

**Comment by Timarrr** [comment]
у тебя не сгенерировались хедеры из .ui файлов, почисть весь билд и попробуй заново

**Comment by VAFA0000** [comment]
Спасибо но теперь ошибка
C:\Users\E5-2650V2\Desktop\RovUI2-master\thrustersetupdialog.cpp:13: ошибка: invalid use of incomplete type 'class Ui::ThrusterSetupDialog'
..\RovUI2-master\thrustersetupdialog.cpp:13:7: error: invalid use of incomplete type 'class Ui::ThrusterSetupDialog'
   13 |     ui->setupUi(this);
      |       ^~
..\RovUI2-master\thrustersetupdialog.h:9:11: note: forward declaration of 'class Ui::ThrusterSetupDialog'
    9 |     class ThrusterSetupDialog;
      |           ^~~~~~~~~~~~~~~~~~~
